config/routes.rb
Rails.application.routes.draw do
  resources :posts
  
  resources :loans do
  
  member do
      get :step1
      get :step2
      get :step3
      get :step4
      get :step5
    end
  end 
  
  devise_for :users
    root to: 'pages#home'
    
    get 'about', to: 'pages#about'
    
    get 'careers', to: 'pages#careers'

    get 'privacy', to: 'pages#privacy'
  
    get 'terms', to: 'pages#terms'
  
    get 'knowledge', to: 'pages#knowledge'
    
    get 'products', to: 'pages#products'
    
    get 'blog', to: 'pages#blog'
    
    get 'why_flipbank', to: 'pages#why_flipbank'
    
    get 'programs', to: 'pages#programs'
    
    get 'how_it_works', to: 'pages#how_it_works'
    
    get 'partners', to: 'pages#partners'
    
    get 'contact-us', to: 'contacts#new', as: 'new_contact'
    
    get 'practice_app1', to: 'pages#practice_app1'
    
    get 'practice_app2', to: 'pages#practice_app2'
    
    get 'practice_app3', to: 'pages#practice_app3'
    
    get 'practice_app4', to: 'pages#practice_app4'
     
    get 'practice_app5', to: 'pages#practice_app5'
    
    get 'show', to: 'pages#show'
    
    get 'show2', to: 'pages#show2'
    
    get 'kc_2', to: 'pages#kc_2'
    
    get 'kc_3', to: 'pages#kc_3'
    
    get 'kc_4', to: 'pages#kc_4'
    
    get 'kc_5', to: 'pages#kc_5'
    
    get 'kc_6', to: 'pages#kc_6'
    
    get 'kc_7', to: 'pages#kc_7'
    
    get 'kc_8', to: 'pages#kc_8'
    
    get 'kc_9', to: 'pages#kc_9'
    
    get 'kc_10', to: 'pages#kc_10'
    
    get 'prod_1', to: 'pages#prod_1'
    
    get 'prod_2', to: 'pages#prod_2'
    
    get 'prod_3', to: 'pages#prod_3'
    
    get 'prod_4', to: 'pages#prod_4'
    
    get 'marketplace', to: 'pages#marketplace'
    
    get 'investors', to: 'pages#investors'
    
    get 'listings', to: 'pages#listings'
    
    get 'analyzer', to: 'pages#analyzer'
    
    get 'dashboard', to: 'pages#dashboard'
    
    get 'quick_start', to: 'pages#quick_start'
    
    get 'thank_you', to: 'pages#thank_you'
    
    resources :contacts, only: :create
end

app/views/layouts/_footer.html.erb
<!--Social Media--> 	
  <div class="social">
    <h3>Why Keep Us a Secret? SHARE us with your friends!</h3>
  	<ul>
  	  <li><%=link_to image_tag("facebook.png"), "https://www.facebook.com/Flipbank-765050520297244/?skip_nax_wizard=true" %> </li>
  		<li><%=link_to image_tag("twitter.png"), "http://www.twitter.com/flipbank_usa" %> </li>
  		<li><%=link_to image_tag("youtube.png"), "https://www.youtube.com/channel/UCOsXvyuqfPhTpn0zxWuiqoQ?guided_help_flow=3" %> </li>
  		<li><%=link_to image_tag("instagram.png"), "http://www.instagram.com/flipbank_usa" %> </li>
  		<li><%=link_to image_tag("snapchat-48.png"), "http://www.snapchat.com/add/flipbank" %> </li>
  		<li><%=link_to image_tag("linkedin.png"), "http://www.linkedin.com/company/flipbank/" %> </li>

  	</ul>
  </div>
  
  <!--Footer-->
  	<div class="mainfoot container">
  	<div class="row">
  	<div class="col-md-3 col-xs-12">
  		<ul>
  			<li><strong>FUNDING OPTIONS</strong></li><hr><br>
  			<li class="mainfoot1"><%= link_to 'Rehab Loans', products_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Bridge Funding', products_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Term Lending', products_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Blanket Loans', products_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Knowledge Center', knowledge_path %></li>
  		</ul>
  	</div>
  	
  	<div class="col-md-2 col-xs-12">
  		<ul>
  			<li><strong>ABOUT US</strong></li><hr><br>
  			<li class="mainfoot1"><%= link_to 'Our Process', about_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Projects', about_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'FAQ', about_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Careers', careers_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Blog', posts_path %></li>
  		</ul>
  	</div>
  	
  	<div class="col-md-3 col-xs-12">
  		<ul>
  			<li><strong>PARTNER WITH US</strong></li><hr><br>
  			<li class="mainfoot1"><%= link_to 'Brokers', partners_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Investors', investors_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Marketplace', marketplace_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Current Listings', listings_path %></li><br>
  			<li class="mainfoot1"><%= link_to 'Flipbank Analyzer', analyzer_path %></li>
  		</ul>
  	</div>
  	
  	<div class="foothead col-md-4 col-xs-12">
  		<ul>
  			<li><strong>GET STARTED</strong></li><hr><br>
  			<li><a href="#"><span class="fa fa-mobile">&nbsp;1-312-522-6708</span></a></li><br>
  			<li><a href="#"><span class="fa fa-envelope-o">&nbsp;info@flipbank.com</span></a></li><br>
  			<li><a href="#"><span class="fa fa-comment">&nbsp;Live Chat</span></a></li><br>
  			<%= link_to '<button type="button" class="btn btn-lg">APPLY NOW</button>'.html_safe, practice_app1_path %>
  		</ul>
  	</div>
  	
  	</div>
  	</div><!--close footer-->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "/", class: "navbar-brand" do %>
          <%= image_tag("FLIPBANK_1.png", size: "202x45") %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <div class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-primary navbar-btn" %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: "btn btn-primary navbar-btn" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success navbar-btn" %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
          <li class="navtext"><%= link_to 'Why FlipBank?', why_flipbank_path %></li>
          <li class="navtext"><%= link_to 'Programs', products_path %></li>
          <li class="navtext"><%= link_to 'How It Works', how_it_works_path %></li>
          <li class="navtext"><%= link_to 'Partners', partners_path %></li>
          <li class="navtext"><%= link_to "Contact Us", new_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header_app.html.erb
<nav class="navbar navbar-app">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "/", class: "navbar-brand" do %>
          <%= image_tag("FLIPBANK_1.png", size: "202x45") %>
      <% end %>
    </div>
      <ul class="nav navbar-nav navbar-right">
          <li class="phone"><span class="leadApp1">Call Us Anytime</span><br><span class="leadApp">(312) 522-6708</span></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portalapp</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
    <script>window.sr = ScrollReveal();</script>
  </head>

  <body>
    
    <div class="container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
    </div>
    <%= yield %>
    
    <script>
    
    sr.reveal('.sidebar', {
        duration: 2000,
        origin: 'right'
        distance: '200px'
    })
    
</script>
  </body>
</html>